export register = {
    r32: ['eax', 'ecx', 'edx', 'ebx', 'esp', 'ebp', 'esi', 'edi'],
    r16: ['ax', 'cx', 'dx', 'bx', 'sp', 'bp', 'si', 'di'],
    r8: ['al', 'cl', 'dl', 'bl', 'ah', 'ch', 'dh', 'bh'],
    sreg: ['es', 'cs', 'ss', 'ds', 'fs', 'gs'],
};

export default {
    add: [
        {opcode: '00', args: ['r/m8', 'r8']},
        {opcode: '66 01', args: ['r/m16', 'r16']},
        {opcode: '01', args: ['r/m32', 'r32']},
        {opcode: '02', args: ['r8', 'r/m8']},
        {opcode: '66 03', args: ['r16', 'r/m16']},
        {opcode: '03', args: ['r32', 'r/m32']},
        {opcode: '04', args: ['al', 'imm8']},
        {opcode: '66 05', args: ['ax', 'imm16']},
        {opcode: '05', args: ['eax', 'imm32']},
        {opcode: '80 /0', args: ['r/m8', 'imm8']},
        {opcode: '66 81 /0', args: ['r/m16', 'imm16']},
        {opcode: '81 /0', args: ['r/m32', 'imm32']},
        {opcode: '82 /0', args: ['r/m8', 'imm8']},
        {opcode: '66 83 /0', args: ['r/m16', 'imm8']},
        {opcode: '83 /0', args: ['r/m32', 'imm8']},
    ],
    and: [
        {opcode: '20', args: ['r/m8', 'r8']},
        {opcode: '66 21', args: ['r/m16', 'r16']},
        {opcode: '21', args: ['r/m32', 'r32']},
        {opcode: '22', args: ['r8', 'r/m8']},
        {opcode: '66 23', args: ['r16', 'r/m16']},
        {opcode: '23', args: ['r32', 'r/m32']},
        {opcode: '24', args: ['al', 'imm8']},
        {opcode: '66 25', args: ['ax', 'imm16']},
        {opcode: '25', args: ['eax', 'imm32']},
        {opcode: '80 /4', args: ['r/m8', 'imm8']},
        {opcode: '66 81 /4', args: ['r/m16', 'imm16']},
        {opcode: '81 /4', args: ['r/m32', 'imm32']},
        {opcode: '82 /4', args: ['r/m8', 'imm8']},
        {opcode: '66 83 /4', args: ['r/m16', 'imm8']},
        {opcode: '83 /4', args: ['r/m32', 'imm8']},
    ],
    cmp: [
        {opcode: '38', args: ['r/m8', 'r8']},
        {opcode: '66 39', args: ['r/m16', 'r16']},
        {opcode: '39', args: ['r/m32', 'r32']},
        {opcode: '3a', args: ['r8', 'r/m8']},
        {opcode: '66 3b', args: ['r16', 'r/m16']},
        {opcode: '3b', args: ['r32', 'r/m32']},
        {opcode: '3c', args: ['al', 'imm8']},
        {opcode: '66 3d', args: ['ax', 'imm16']},
        {opcode: '3d', args: ['eax', 'imm32']},
        {opcode: '80 /7', args: ['r/m8', 'imm8']},
        {opcode: '66 81 /7', args: ['r/m16', 'imm16']},
        {opcode: '81 /7', args: ['r/m32', 'imm32']},
        {opcode: '82 /7', args: ['r/m8', 'imm8']},
        {opcode: '66 83 /7', args: ['r/m16', 'imm8']},
        {opcode: '83 /7', args: ['r/m32', 'imm8']},
    ],
    neg: [
        {opcode: 'f6 /3', args: ['r/m8']},
        {opcode: '66 f7 /3', args: ['r/m16']},
        {opcode: 'f7 /3', args: ['r/m32']},
    ],
    not: [
        {opcode: 'f6 /2', args: ['r/m8']},
        {opcode: '66 f7 /2', args: ['r/m16']},
        {opcode: 'f7 /2', args: ['r/m32']},
    ],
    or: [
        {opcode: '08', args: ['r/m8', 'r8']},
        {opcode: '66 09', args: ['r/m16', 'r16']},
        {opcode: '09', args: ['r/m32', 'r32']},
        {opcode: '0a', args: ['r8', 'r/m8']},
        {opcode: '66 0b', args: ['r16', 'r/m16']},
        {opcode: '0b', args: ['r32', 'r/m32']},
        {opcode: '0c', args: ['al', 'imm8']},
        {opcode: '66 0d', args: ['ax', 'imm16']},
        {opcode: '0d', args: ['eax', 'imm32']},
        {opcode: '80 /1', args: ['r/m8', 'imm8']},
        {opcode: '66 81 /1', args: ['r/m16', 'imm16']},
        {opcode: '81 /1', args: ['r/m32', 'imm32']},
        {opcode: '82 /1', args: ['r/m8', 'imm8']},
        {opcode: '66 83 /1', args: ['r/m16', 'imm8']},
        {opcode: '83 /1', args: ['r/m32', 'imm8']},
    ],
    int: [
        {opcode: 'cc', args: ['3']},
        {opcode: 'cd', args: ['imm8']},
    ],
    iret: [
        {opcode: 'cf', args: []},
    ],
    lea: [
        {opcode: '66 8d', args: ['r16', 'm']},
        {opcode: '8d', args: ['r32', 'm']},
    ],
    sub: [
        {opcode: '28', args: ['r/m8', 'r8']},
        {opcode: '66 29', args: ['r/m16', 'r16']},
        {opcode: '29', args: ['r/m32', 'r32']},
        {opcode: '2a', args: ['r8', 'r/m8']},
        {opcode: '66 2b', args: ['r16', 'r/m16']},
        {opcode: '2b', args: ['r32', 'r/m32']},
        {opcode: '2c', args: ['al', 'imm8']},
        {opcode: '66 2d', args: ['ax', 'imm16']},
        {opcode: '2d', args: ['eax', 'imm32']},
        {opcode: '80 /5', args: ['r/m8', 'imm8']},
        {opcode: '66 81 /5', args: ['r/m16', 'imm16']},
        {opcode: '81 /5', args: ['r/m32', 'imm32']},
        {opcode: '82 /5', args: ['r/m8', 'imm8']},
        {opcode: '66 83 /5', args: ['r/m16', 'imm8']},
        {opcode: '83 /5', args: ['r/m32', 'imm8']},
    ],
    xor: [
        {opcode: '30', args: ['r/m8', 'r8']},
        {opcode: '66 31', args: ['r/m16', 'r16']},
        {opcode: '31', args: ['r/m32', 'r32']},
        {opcode: '32', args: ['r8', 'r/m8']},
        {opcode: '66 33', args: ['r16', 'r/m16']},
        {opcode: '33', args: ['r32', 'r/m32']},
        {opcode: '34', args: ['al', 'imm8']},
        {opcode: '66 35', args: ['ax', 'imm16']},
        {opcode: '35', args: ['eax', 'imm32']},
        {opcode: '80 /6', args: ['r/m8', 'imm8']},
        {opcode: '66 81 /6', args: ['r/m16', 'imm16']},
        {opcode: '81 /6', args: ['r/m32', 'imm32']},
        {opcode: '82 /6', args: ['r/m8', 'imm8']},
        {opcode: '66 83 /6', args: ['r/m16', 'imm8']},
        {opcode: '83 /6', args: ['r/m32', 'imm8']},
    ],
    call: [
        {opcode: '66 e8', args: ['rel16']},
        {opcode: 'e8', args: ['rel32']},
        {opcode: '67 ff /2', args: ['r/m16']},
        {opcode: 'ff /2', args: ['r/m32']},
    ],
    callf: [
        {opcode: '66 9a', args: ['ptr16:16']},
        {opcode: '9a', args: ['ptr16:32']},
        {opcode: '67 ff /3', args: ['m16:16']},
        {opcode: 'ff /3', args: ['m16:32']},
    ],
    jmp: [
        {opcode: '66 e9', args: ['rel16']},
        {opcode: 'e9', args: ['rel32']},
        {opcode: 'eb', args: ['rel8']},
        {opcode: '67 ff /4', args: ['r/m16']},
        {opcode: 'ff /4', args: ['r/m32']},
    ],
    jmpf: [
        {opcode: '66 ea', args: ['ptr16:16']},
        {opcode: 'ea', args: ['ptr16:32']},
        {opcode: '67 ff /5', args: ['m16:16']},
        {opcode: 'ff /5', args: ['m16:32']},
    ],
    pushf: [
        {opcode: '9c', args: []},
    ],
    popf: [
        {opcode: '9d', args: []},
    ],
};
